# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2024-12-27T13:00:29+00:00

from __future__ import annotations

from typing import NotRequired, TypedDict


class State(TypedDict):
    name: str
    category: str
    description: NotRequired[str]


class FromResource(TypedDict):
    id: NotRequired[str]
    displayedValue: str


class ToResource(TypedDict):
    id: NotRequired[str]
    displayedValue: str


class OperationAmount(TypedDict):
    amount: float
    currencyCode: str


class NationalAmount(TypedDict):
    amount: float
    currencyCode: str


class Attributes(TypedDict):
    copyable: bool
    nfc: bool
    cashReceipt: bool
    compositePayment: bool


class BillingAmount(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    amount: float
    currencyCode: str


class Commission(TypedDict):
    amount: int
    currencyCode: str


class Operation(TypedDict):
    uohId: str
    date: str
    creationChannel: int
    form: str
    state: State
    description: str
    fromResource: NotRequired[FromResource]
    toResource: NotRequired[ToResource]
    correspondent: str
    operationAmount: NotRequired[OperationAmount]
    nationalAmount: NotRequired[NationalAmount]
    attributes: Attributes
    classificationCode: NotRequired[int]
    type: str
    billingAmount: NotRequired[BillingAmount]
    authorizationDocId: NotRequired[str]
    externalId: str
    isFinancial: bool
    operationComment: NotRequired[str]
    ufsId: NotRequired[str]
    imageUrl: NotRequired[str]
    isHidden: NotRequired[bool]
    commission: NotRequired[Commission]


class Body(TypedDict):
    operations: list[Operation]


class Model(TypedDict):
    success: bool
    body: Body
