# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2024-12-27T15:53:45+00:00

from __future__ import annotations

from typing import TypedDict


class ItemListItem(TypedDict):
    accountNumber: str
    credit: float | None
    currency: str
    transactionType: str | None
    transactionId: str
    debit: float | None
    description: str
    isCardBlock: bool
    operationDateTime: str
    stmtEntryId: str
    canRepeat: bool
    canReverse: bool
    canTemplate: bool
    amountEquivalent: float
    operationType: str
    operationTypeId: None


class TransactionPagingList(TypedDict):
    itemList: list[ItemListItem]


class Data(TypedDict):
    transactionPagingList: TransactionPagingList


class Model(TypedDict):
    data: Data
