# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2024-12-27T14:39:48+00:00

from __future__ import annotations

from typing import NotRequired, TypedDict


class Transaction(TypedDict):
    transactionSystemId: str
    transactionId: str


class Colour(TypedDict):
    light: str
    dark: str


class ParentCategory(TypedDict):
    id: int
    logo: str
    name: str
    colour: Colour


class OperationAmount(TypedDict):
    currency: str
    sum: float


class TransactionAmount(TypedDict):
    currency: str
    sum: float


class Receipt(TypedDict):
    caption: str
    index: int


class Property(TypedDict):
    key: str
    value: str
    receipt: NotRequired[Receipt]


class Template(TypedDict):
    list: str
    view: str
    receipt: NotRequired[str]


class FeeAmount(TypedDict):
    currency: str
    sum: float


class Operation(TypedDict):
    transactions: list[Transaction]
    authorizationCode: str
    account: str
    accountProductId: str
    parentCategory: ParentCategory
    operationName: str
    fullOperationName: str
    debet: bool
    transactionDate: str
    processedDate: str
    operationAmount: OperationAmount
    transactionAmount: TransactionAmount
    isHold: bool
    status: str
    eventTime: str
    properties: list[Property]
    operationDate: str
    chainId: str
    operationId: str
    internalId: str
    operationType: str
    message: NotRequired[str]
    template: NotRequired[Template]
    feeAmount: NotRequired[FeeAmount]
    operationCode: NotRequired[str]


class Model(TypedDict):
    operations: list[Operation]
